import assert from "node:assert/strict";
import { addon, createSurface, delay } from "./native-driver.mjs";
const surface = await createSurface();
const report = [];
try {
  addon.setAccess(surface.id, true, 1);
  const emoji = Buffer.from("👨‍👩‍👧 🇯🇵 👋🏽 e\u0301");
  for (const byte of emoji) await surface.write(Buffer.from([byte]));
  assert.ok(surface.dump().includes(emoji.toString()));
  report.push("半截 UTF-8：逐字节恢复多码点输出");
  await surface.write("\x1b["); await surface.write("2J\x1b[HCSI_OK");
  assert.ok(surface.dump().startsWith("CSI_OK"));
  report.push("半截 CSI：续块按转义序列解析");
  await surface.write("\x1b[?1049hALT_OLD\x1b[31m\x1b[");
  await surface.reset();
  await surface.write("FRESH\r\n", true);
  const replaced = surface.dump();
  assert.ok(replaced.startsWith("FRESH")); assert.ok(!replaced.includes("ALT_OLD"));
  await surface.write("\x1b[?1049l");
  assert.ok(surface.dump().startsWith("FRESH"), "replacement 不能残留旧 alt screen");
  report.push("replacement：清除半截 CSI、旧 alt screen 与旧文本");
  await surface.write(Buffer.from([0xf0, 0x9f]));
  await surface.reset(); await surface.write("UTF8_RESET", true);
  assert.ok(surface.dump().startsWith("UTF8_RESET"));
  report.push("replacement：清除半截 UTF-8 parser 状态");
  await surface.reset();
  const size = await surface.frame(420, 300);
  const columns = size.x;
  assert.ok(columns > 2);
  await surface.write("X".repeat(columns - 1) + "界Z");
  const lines = surface.dump().split("\n");
  assert.equal(lines[0].trimEnd(), "X".repeat(columns - 1));
  assert.ok(lines[1].startsWith("界Z"));
  report.push(`resize 栅栏：新列数 ${columns}，首块宽字符按新列数换行`);
  await surface.reset(); surface.events.length = 0;
  await surface.write("\x1b[c\x1b[5n\x1b[6n", true);
  await delay(200);
  assert.equal(surface.events.filter((event) => event.kind === 2).length, 0, "replay 不允许 DA/DSR 回写");
  await surface.write("\x1b[c\x1b[6n");
  await surface.wait(2);
  report.push("replay 无 DA/DSR 回写，实时同序列可产生回写（非门禁掩盖）");
  console.log(JSON.stringify({ gate: "G6", cases: report }, null, 2));
} finally { await surface.destroy(); }
