// swift-tools-version:6.0
import PackageDescription

// 上游源码按 manifest.json 固定，不依赖上游的失效 Swift manifest。
let package = Package(
    name: "CofluxNativeGrammars",
    products: [.library(name: "TreeSitterZsh", targets: ["TreeSitterZsh"]),
               .library(name: "TreeSitterGroovy", targets: ["TreeSitterGroovy"]),
               .library(name: "TreeSitterPerl", targets: ["TreeSitterPerl"]),
               .library(name: "TreeSitterPowershell", targets: ["TreeSitterPowershell"]),
               .library(name: "TreeSitterSvelte", targets: ["TreeSitterSvelte"]),
               .library(name: "TreeSitterVue", targets: ["TreeSitterVue"]),
               .library(name: "TreeSitterLess", targets: ["TreeSitterLess"]),
               .library(name: "TreeSitterDart", targets: ["TreeSitterDart"]),
               .library(name: "TreeSitterErlang", targets: ["TreeSitterErlang"]),
               .library(name: "TreeSitterGraphQL", targets: ["TreeSitterGraphQL"]),
               .library(name: "TreeSitterJSON5", targets: ["TreeSitterJSON5"]),
               .library(name: "TreeSitterProto", targets: ["TreeSitterProto"])],
    targets: [.target(name: "TreeSitterZsh", path: "Zsh",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterGroovy", path: "Groovy",
                      exclude: ["LICENSE"], sources: ["src/parser.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterPerl", path: "Perl",
                      exclude: ["LICENSE", "BSEARCH-LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterPowershell", path: "Powershell",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterSvelte", path: "Svelte",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterVue", path: "Vue",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterLess", path: "Less",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterDart", path: "Dart",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterErlang", path: "Erlang",
                      exclude: ["LICENSE"], sources: ["src/parser.c", "src/scanner.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterGraphQL", path: "GraphQL",
                      exclude: ["LICENSE"], sources: ["src/parser.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterJSON5", path: "JSON5",
                      exclude: ["LICENSE"], sources: ["src/parser.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")]),
              .target(name: "TreeSitterProto", path: "Proto",
                      exclude: ["LICENSE"], sources: ["src/parser.c"],
                      publicHeadersPath: "include", cSettings: [.headerSearchPath("src")])],
    cLanguageStandard: .c11
)
